using UnityEditor;
using UnityEngine;

namespace UnityEssentials
{
    public static class Icon
    {
        public static string GetIconReferenceByName(IconNames icon)
        {
#if UNITY_EDITOR
            string iconString = EditorIcons.Icons[(int)icon];

            if (!string.IsNullOrEmpty(iconString))
                return iconString;
#endif
            return null;
        }

        public static Texture2D GetIconTexture(IconNames icon)
        {
#if UNITY_EDITOR
            string iconString = EditorIcons.Icons[(int)icon];

            if (!string.IsNullOrEmpty(iconString))
                return EditorGUIUtility.IconContent(iconString).image as Texture2D;
#endif
            return null;
        }
    }

    public enum IconNames
    {
        None = -1, Help, Popup, aboutwindowmainheader, ageialogo, AlphabeticalSorting, AnimationAddEvent,
        AnimationAddKeyframe, AnimationEventMarker, AnimationFirstKey, AnimationLastKey,
        AnimationNextKey, AnimationPlay, AnimationPrevKey, AnimationRecord, AnimationSequencerLink,
        animationanimated, animationdopesheetkeyframe, animationkeyframe, animationnocurve,
        animationvisibilitytoggleoff, animationvisibilitytoggleon, AnimationWrapModeMenu, AssemblyLock,
        AssetStore, AudioMixer, AvatarCompass, AvatarControllerLayer, AvatarControllerLayerHover,
        AvatarControllerLayerSelected, BodyPartPicker, BodySilhouette, DotFill, DotFrame, DotFrameDotted,
        DotSelection, Head, HeadIk, HeadZoom, HeadZoomSilhouette, LeftArm, LeftFeetIk, LeftFingers,
        LeftFingersIk, LeftHandZoom, LeftHandZoomSilhouette, LeftLeg, MaskEditorRoot, RightArm, RightFeetIk,
        RightFingers, RightFingersIk, RightHandZoom, RightHandZoomSilhouette, RightLeg, Torso, AvatarPivot,
        back, back2x, beginButtonOn, beginButton, blendKey, blendKeyOverlay, blendKeySelected,
        blendSampler, blueGroove, BuildSettingsAndroid, BuildSettingsAndroidSmall, BuildSettingsBroadcom,
        BuildSettingsEditor, BuildSettingsEditorSmall, BuildSettingsFacebook,
        BuildSettingsFacebookSmall, BuildSettingsFlashPlayer, BuildSettingsFlashPlayerSmall,
        BuildSettingsiPhone, BuildSettingsiPhoneSmall, BuildSettingsLumin, BuildSettingsLuminsmall,
        BuildSettingsMetro, BuildSettingsMetroSmall, BuildSettingsN3DS, BuildSettingsN3DSSmall,
        BuildSettingsPS4, BuildSettingsPS4Small, BuildSettingsPSM, BuildSettingsPSMSmall,
        BuildSettingsPSP2, BuildSettingsPSP2Small, BuildSettingsSelectedIcon, BuildSettingsStandalone,
        BuildSettingsStandaloneSmall, BuildSettingsStandaloneBroadcomSmall,
        BuildSettingsStandaloneGLES20EmuSmall, BuildSettingsStandaloneGLESEmu,
        BuildSettingsStandaloneGLESEmuSmall, BuildSettingsSwitch, BuildSettingsSwitchSmall,
        BuildSettingstvOS, BuildSettingstvOSSmall, BuildSettingsWeb, BuildSettingsWebSmall,
        BuildSettingsWebGL, BuildSettingsWebGLSmall, BuildSettingsWP8, BuildSettingsWP8Small,
        BuildSettingsXbox360, BuildSettingsXbox360Small, BuildSettingsXboxOne,
        BuildSettingsXboxOneSmall, BuildSettingsXiaomi, CameraGizmo, CheckerFloor, Clipboard,
        ClothInspectorPaintTool, ClothInspectorPaintValue, ClothInspectorSelectTool,
        ClothInspectorSettingsTool, ClothInspectorViewValue, CloudConnect, CollabBuild,
        CollabBuildFailed, CollabBuildSucceeded, CollabFileAdded, CollabFileConflict, CollabFileDeleted,
        CollabFileIgnored, CollabFileMoved, CollabFileUpdated, CollabFolderAdded, CollabFolderConflict,
        CollabFolderDeleted, CollabFolderIgnored, CollabFolderMoved, CollabFolderUpdated,
        CollabNoInternet, Collab, CollabWarning, CollabConflict, CollabError, CollabNew, CollabOffline,
        CollabProgress, CollabPull, CollabPush, ColorPickerColorCycle, ColorPickerCycleColor,
        ColorPickerCycleSlider, ColorPickerSliderCycle, consoleerroriconinactivesml, consoleerroricon,
        consoleerroriconsml, consoleinfoicon, consoleinfoiconsml, consolewarniconinactivesml,
        consolewarnicon, consolewarniconsml, curvekeyframe, curvekeyframeselected,
        curvekeyframeselectedoverlay, curvekeyframesemiselectedoverlay, curvekeyframeweighted, CustomSorting,
        dPopup, daboutwindowmainheader, dageialogo, dAlphabeticalSorting, dAnimationAddEvent,
        dAnimationAddKeyframe, dAnimationEventMarker, dAnimationFirstKey, dAnimationLastKey,
        dAnimationNextKey, dAnimationPlay, dAnimationPrevKey, dAnimationRecord,
        dAnimationSequencerLink, danimationanimated, danimationkeyframe, danimationnocurve,
        danimationvisibilitytoggleoff, danimationvisibilitytoggleon, dAnimationWrapModeMenu,
        dASBadgeDelete, dASBadgeNew, dAssemblyLock, dAssetStore, dAudioMixer,
        dAvatarBlendBackground, dAvatarBlendLeft, dAvatarBlendLeftA, dAvatarBlendRight,
        dAvatarBlendRightA, dAvatarCompass, dAvatarPivot, dback, dback2x, dbeginButtonOn,
        dbeginButton, dblueGroove, dBuildSettingsAndroid, dBuildSettingsAndroidSmall,
        dBuildSettingsBroadcom, dBuildSettingsFlashPlayer, dBuildSettingsFlashPlayerSmall,
        dBuildSettingsiPhone, dBuildSettingsiPhoneSmall, dBuildSettingsLumin,
        dBuildSettingsLuminsmall, dBuildSettingsPS4, dBuildSettingsPS4Small, dBuildSettingsPSP2,
        dBuildSettingsPSP2Small, dBuildSettingsSelectedIcon, dBuildSettingsStandalone,
        dBuildSettingsStandaloneSmall, dBuildSettingstvOS, dBuildSettingstvOSSmall,
        dBuildSettingsWeb, dBuildSettingsWebSmall, dBuildSettingsWebGL, dBuildSettingsWebGLSmall,
        dBuildSettingsXbox360, dBuildSettingsXbox360Small, dBuildSettingsXboxOne,
        dBuildSettingsXboxOneSmall, dCheckerFloor, dCloudConnect, dCollabFileAdded,
        dCollabFileConflict, dCollabFileDeleted, dCollabFileIgnored, dCollabFileMoved,
        dCollabFileUpdated, dCollabFolderAdded, dCollabFolderConflict, dCollabFolderDeleted,
        dCollabFolderIgnored, dCollabFolderMoved, dCollabFolderUpdated, dColorPickerCycleColor,
        dColorPickerCycleSlider, dconsoleerroricon, dconsoleerroriconsml, dconsoleinfoicon,
        dconsoleinfoiconsml, dconsolewarnicon, dconsolewarniconsml, dcurvekeyframe,
        dcurvekeyframeselected, dcurvekeyframeselectedoverlay, dcurvekeyframesemiselectedoverlay,
        dcurvekeyframeweighted, dCustomSorting, dDefaultSorting, dEditCollider, deditcollision16,
        deditconstraints16, dediticonsml, dendButtonOn, dendButton, deyeDropperLarge,
        deyeDroppersml, dFavorite, dFilterByLabel, dFilterByType, dFilterSelectedOnly,
        dFilterSelectedOnly2x, dforward, dforward2x, dGEAR, dGroove, dHorizontalSplit,
        dicondropdown, dInspectorLock, dJointAngularLimits, dleftBracket, dLighting,
        dLightmapEditorWindowTitle, dLookDevCenterLight, dLookDevCenterLight2x, dLookDevClose,
        dLookDevClose2x, dLookDevEnvRotation, dLookDevEnvRotation2x, dLookDevMirrorViews,
        dLookDevMirrorViews2x, dLookDevMirrorViewsActive, dLookDevMirrorViewsActive2x,
        dLookDevMirrorViewsInactive, dLookDevMirrorViewsInactive2x, dLookDevObjRotation,
        dLookDevObjRotation2x, dLookDevPaneOption, dLookDevPaneOption2x, dLookDevResetEnv,
        dLookDevResetEnv2x, dLookDevShadow, dLookDevShadow2x, dLookDevSideBySide,
        dLookDevSideBySide2x, dLookDevSingle1, dLookDevSingle12x, dLookDevSingle2,
        dLookDevSingle22x, dLookDevSplit, dLookDevSplit2x, dLookDevZone, dLookDevZone2x,
        dMirror, dmodellarge, dmonologo, dMoveToolon, dMoveTool, dNavigation, dOcclusion,
        dP4AddedLocal, dP4AddedRemote, dP4CheckOutLocal, dP4CheckOutRemote, dP4Conflicted,
        dP4DeletedLocal, dP4DeletedRemote, dP4Local, dP4LockedLocal, dP4LockedRemote,
        dP4OutOfSync, dParticleEffect, dPauseButtonOn, dPauseButton, dPlayButtonOn, dPlayButton,
        dPlayButtonProfileOn, dPlayButtonProfile, dplayLoopOff, dplayLoopOn, dpreAudioAutoPlayOff,
        dpreAudioAutoPlayOn, dpreAudioLoopOff, dpreAudioLoopOn, dpreAudioPlayOff, dpreAudioPlayOn,
        dPreMatCube, dPreMatCylinder, dPreMatLight0, dPreMatLight1, dPreMatSphere, dPreMatTorus,
        dPresetContext, dPreTextureAlpha, dPreTextureMipMapHigh, dPreTextureMipMapLow, dPreTextureRGB,
        dProfilerAudio, dProfilerCPU, dProfilerFirstFrame, dProfilerGPU, dProfilerLastFrame,
        dProfilerMemory, dProfilerNetwork, dProfilerNextFrame, dProfilerPhysics, dProfilerPrevFrame,
        dProfilerRecord, dProfilerRendering, dProfilerVideo, dProfilerColumnWarningCount, dProject,
        dRectToolOn, dRectTool, dRectTransformBlueprint, dRectTransformRaw, dredGroove, dRefresh,
        drenderdoc, drightBracket, dRotateToolOn, dRotateTool, dScaleToolOn, dScaleTool,
        dSceneViewAlpha, dSceneViewAudio, dSceneViewFx, dSceneViewLighting, dSceneViewOrtho,
        dSceneViewRGB, dScrollShadow, dSettings, dSettingsIcon, dSocialNetworksFacebookShare,
        dSocialNetworksLinkedInShare, dSocialNetworksTweet, dSocialNetworksUDNOpen, dSpeedScale,
        dStepButtonOn, dStepButton, dStepLeftButtonOn, dStepLeftButton, dSVNAddedLocal,
        dSVNConflicted, dSVNDeletedLocal, dSVNLocal, dSVNLockedLocal, dSVNOutOfSync, dtabnext,
        dtabnext2x, dtabprev, dtabprev2x, dTerrainInspectorTerrainToolLowerOn,
        dTerrainInspectorTerrainToolLowerAlt, dTerrainInspectorTerrainToolPlantsOn,
        dTerrainInspectorTerrainToolPlants, dTerrainInspectorTerrainToolPlantsAltOn,
        dTerrainInspectorTerrainToolPlantsAlt, dTerrainInspectorTerrainToolRaiseOn,
        dTerrainInspectorTerrainToolRaise, dTerrainInspectorTerrainToolSetheightOn,
        dTerrainInspectorTerrainToolSetheight, dTerrainInspectorTerrainToolSetheightAltOn,
        dTerrainInspectorTerrainToolSetheightAlt, dTerrainInspectorTerrainToolSettingsOn,
        dTerrainInspectorTerrainToolSettings, dTerrainInspectorTerrainToolSmoothHeightOn,
        dTerrainInspectorTerrainToolSmoothHeight, dTerrainInspectorTerrainToolSplatOn,
        dTerrainInspectorTerrainToolSplat, dTerrainInspectorTerrainToolSplatAltOn,
        dTerrainInspectorTerrainToolSplatAlt, dTerrainInspectorTerrainToolTreesOn,
        dTerrainInspectorTerrainToolTrees, dTerrainInspectorTerrainToolTreesAltOn,
        dTerrainInspectorTerrainToolTreesAlt, dTimelineDigIn, dTimelineEditModeMixOFF,
        dTimelineEditModeMixON, dTimelineEditModeReplaceOFF, dTimelineEditModeReplaceON,
        dTimelineEditModeRippleOFF, dTimelineEditModeRippleON, dTimelineSelector, dToolbarMinus,
        dToolbarPlusMore, dToolbarPlus, dToolHandleCenter, dToolHandleGlobal, dToolHandleLocal,
        dToolHandlePivot, dtranp, dTransformToolOn, dTransformTool, dtreeicon, dtreeiconbranch,
        dtreeiconbranchfrond, dtreeiconfrond, dtreeiconleaf, dTreeEditorAddBranches,
        dTreeEditorAddLeaves, dTreeEditorBranchOn, dTreeEditorBranch, dTreeEditorBranchFreeHandOn,
        dTreeEditorBranchFreeHand, dTreeEditorBranchRotateOn, dTreeEditorBranchRotate,
        dTreeEditorBranchScaleOn, dTreeEditorBranchScale, dTreeEditorBranchTranslateOn,
        dTreeEditorBranchTranslate, dTreeEditorDistributionOn, dTreeEditorDistribution,
        dTreeEditorDuplicate, dTreeEditorGeometryOn, dTreeEditorGeometry, dTreeEditorLeafOn,
        dTreeEditorLeaf, dTreeEditorLeafFreeHandOn, dTreeEditorLeafFreeHand, dTreeEditorLeafRotateOn,
        dTreeEditorLeafRotate, dTreeEditorLeafScaleOn, dTreeEditorLeafScale,
        dTreeEditorLeafTranslateOn, dTreeEditorLeafTranslate, dTreeEditorMaterialOn,
        dTreeEditorMaterial, dTreeEditorRefresh, dTreeEditorTrash, dTreeEditorWindOn,
        dTreeEditorWind, dUnityEditorAnimationWindow, dUnityEditorConsoleWindow,
        dUnityEditorDebugInspectorWindow, dUnityEditorFindDependencies, dUnityEditorGameView,
        dUnityEditorHierarchyWindow, dUnityEditorInspectorWindow, dUnityEditorLookDevView,
        dUnityEditorProfilerWindow, dUnityEditorSceneHierarchyWindow, dUnityEditorSceneView,
        dUnityEditorTimelineTimelineWindow, dUnityEditorVersionControl, dUnityLogo, dVerticalSplit,
        dViewToolMoveOn, dViewToolMove, dViewToolOrbitOn, dViewToolOrbit, dViewToolZoomOn,
        dViewToolZoom, dVisibilityOff, dVisibilityOn, dVUMeterTextureHorizontal, dVUMeterTextureVertical,
        dWaitSpin00, dWaitSpin01, dWaitSpin02, dWaitSpin03, dWaitSpin04, dWaitSpin05, dWaitSpin06,
        dWaitSpin07, dWaitSpin08, dWaitSpin09, dWaitSpin10, dWaitSpin11, dWelcomeScreenAssetStoreLogo,
        dwinbtngraph, dwinbtngraphcloseh, dwinbtngraphmaxh, dwinbtngraphminh,
        dwinbtnmacclose, dwinbtnmacclosea, dwinbtnmaccloseh, dwinbtnmacinact, dwinbtnmacmax,
        dwinbtnmacmaxa, dwinbtnmacmaxh, dwinbtnmacmin, dwinbtnmacmina, dwinbtnmacminh,
        dwinbtnwinclose, dwinbtnwinclosea, dwinbtnwincloseh, dwinbtnwinmax, dwinbtnwinmaxa,
        dwinbtnwinmaxh, dwinbtnwinmin, dwinbtnwinmina, dwinbtnwinminh, dwinbtnwinrest,
        dwinbtnwinresta, dwinbtnwinresth, DefaultSorting, EditCollider, editcollision16,
        editconstraints16, editiconsml, endButtonOn, endButton, eyeDropperLarge, eyeDroppersml,
        Favorite, FilterByLabel, FilterByType, FilterSelectedOnly, FilterSelectedOnly2x, forward,
        forward2x, GEAR, GridBoxTool, GridDefault, GridEraserTool, GridFillTool, GridMoveTool,
        GridPaintTool, GridPickingTool, GridSelectTool, Groove, alignhorizontally,
        alignhorizontallycenter, alignhorizontallycenteractive, alignhorizontallyleft,
        alignhorizontallyleftactive, alignhorizontallyright, alignhorizontallyrightactive,
        alignvertically, alignverticallybottom, alignverticallybottomactive, alignverticallycenter,
        alignverticallycenteractive, alignverticallytop, alignverticallytopactive,
        dalignhorizontally, dalignhorizontallycenter, dalignhorizontallycenteractive,
        dalignhorizontallyleft, dalignhorizontallyleftactive, dalignhorizontallyright,
        dalignhorizontallyrightactive, dalignvertically, dalignverticallybottom,
        dalignverticallybottomactive, dalignverticallycenter, dalignverticallycenteractive,
        dalignverticallytop, dalignverticallytopactive, HorizontalSplit, icondropdown,
        InspectorLock, JointAngularLimits, KnobCShape, KnobCShapeMini, leftBracket, Lighting,
        LightmapEditorWindowTitle, Lightmapping, dgreenLight, dlightOff, dlightRim, dorangeLight,
        dredLight, greenLight, lightOff, lightRim, orangeLight, redLight, LockIconOn, LockIcon,
        LookDevCenterLight, LookDevCenterLightl2x, LookDevClose, LookDevClose2x, LookDevEnvRotation,
        LookDevEnvRotation2x, LookDevEyedrop, LookDevLight, LookDevLight2x, LookDevMirrorViewsActive,
        LookDevMirrorViewsActive2x, LookDevMirrorViewsInactive, LookDevMirrorViewsInactive2x,
        LookDevObjRotation, LookDevObjRotation2x, LookDevPaneOption, LookDevPaneOption2x, LookDevResetEnv,
        LookDevResetEnv2x, LookDevShadow, LookDevShadow2x, LookDevShadowFrame, LookDevShadowFrame2x,
        LookDevSideBySide, LookDevSideBySide2x, LookDevSingle1, LookDevSingle12x, LookDevSingle2,
        LookDevSingle22x, LookDevSplit, LookDevSplit2x, LookDevZone, LookDevZone2x, loop, Mirror,
        monologo, MoveToolon, MoveTool, Navigation, Occlusion, P4AddedLocal, P4AddedRemote,
        P4BlueLeftParenthesis, P4BlueRightParenthesis, P4CheckOutLocal, P4CheckOutRemote, P4Conflicted,
        P4DeletedLocal, P4DeletedRemote, P4Local, P4LockedLocal, P4LockedRemote, P4OutOfSync,
        P4RedLeftParenthesis, P4RedRightParenthesis, P4Updating, PackageBadgeDelete, PackageBadgeNew,
        ParticleEffect, PauseButtonOn, PauseButton, PlayButtonOn, PlayButton, PlayButtonProfileOn,
        PlayButtonProfile, playLoopOff, playLoopOn, playSpeed, preAudioAutoPlayOff, preAudioAutoPlayOn,
        preAudioLoopOff, preAudioLoopOn, preAudioPlayOff, preAudioPlayOn, PreMatCube, PreMatCylinder,
        PreMatLight0, PreMatLight1, PreMatQuad, PreMatSphere, PreMatTorus, PresetContext, PreTextureAlpha,
        PreTextureArrayFirstSlice, PreTextureArrayLastSlice, PreTextureMipMapHigh, PreTextureMipMapLow,
        PreTextureRGB, AreaLightGizmo, AreaLightIcon, AssemblyIcon, AssetStoreIcon, AudioMixerViewIcon,
        AudioSourceGizmo, CameraGizmo2, CGProgramIcon, ChorusFilterIcon, CollabChangesIcon,
        CollabChangesConflictIcon, CollabChangesDeletedIcon, CollabConflictIcon, CollabCreateIcon,
        CollabDeletedIcon, CollabEditIcon, CollabExcludeIcon, CollabMovedIcon, csScriptIcon,
        dAudioMixerViewIcon, dCollabChangesIcon, dCollabChangesConflictIcon, dCollabChangesDeletedIcon,
        dCollabConflictIcon, dCollabCreateIcon, dCollabDeletedIcon, dCollabEditIcon,
        dCollabExcludeIcon, dCollabMovedIcon, dGridLayoutGroupIcon, dHorizontalLayoutGroupIcon,
        dPrefabIcon, dPrefabModelIcon, dPrefabVariantIcon, dVerticalLayoutGroupIcon,
        DefaultSlateIcon, DirectionalLightGizmo, DirectionalLightIcon, DiscLightGizmo, DiscLightIcon,
        dllScriptIcon, EchoFilterIcon, FavoriteIcon, FolderIcon, FolderEmptyIcon,
        FolderFavoriteIcon, GameManagerIcon, GridBrushIcon, HighPassFilterIcon,
        HorizontalLayoutGroupIcon, LensFlareGizmo, LightingDataAssetParentIcon, LightProbeGroupGizmo,
        LightProbeProxyVolumeGizmo, LowPassFilterIcon, MainLightGizmo, MetaFileIcon,
        MicrophoneIcon, MuscleClipIcon, ParticleSystemGizmo, PointLightGizmo, PrefabIcon,
        PrefabModelIcon, PrefabOverlayAddedIcon, PrefabOverlayModifiedIcon, PrefabOverlayRemovedIcon,
        PrefabVariantIcon, ProjectorGizmo, RaycastColliderIcon, ReflectionProbeGizmo,
        ReverbFilterIcon, SceneSetIcon, SearchIcon, SoftlockProjectBrowserIcon, SpeedTreeModelIcon,
        SpotLightGizmo, SpotlightIcon, SpriteColliderIcon, svicondot0pix16gizmo,
        svicondot10pix16gizmo, svicondot11pix16gizmo, svicondot12pix16gizmo,
        svicondot13pix16gizmo, svicondot14pix16gizmo, svicondot15pix16gizmo,
        svicondot1pix16gizmo, svicondot2pix16gizmo, svicondot3pix16gizmo,
        svicondot4pix16gizmo, svicondot5pix16gizmo, svicondot6pix16gizmo,
        svicondot7pix16gizmo, svicondot8pix16gizmo, svicondot9pix16gizmo,
        AnimatorControllerIcon, AnimatorStateIcon, AnimatorStateMachineIcon,
        AnimatorStateTransitionIcon, BlendTreeIcon, AnimationWindowEventIcon, AudioMixerControllerIcon,
        DefaultAssetIcon, EditorSettingsIcon, AnyStateNodeIcon, HumanTemplateIcon,
        LightingDataAssetIcon, LightmapParametersIcon, PresetIcon, SceneAssetIcon,
        SubstanceArchiveIcon, AssemblyDefinitionAssetIcon, NavMeshAgentIcon, NavMeshDataIcon,
        NavMeshObstacleIcon, OffMeshLinkIcon, AnalyticsTrackerIcon, AnimationIcon,
        AnimationClipIcon, AimConstraintIcon, dAimConstraintIcon, dLookAtConstraintIcon,
        dParentConstraintIcon, dPositionConstraintIcon, dRotationConstraintIcon,
        dScaleConstraintIcon, LookAtConstraintIcon, ParentConstraintIcon, PositionConstraintIcon,
        RotationConstraintIcon, ScaleConstraintIcon, AnimatorIcon, AnimatorOverrideControllerIcon,
        AreaEffector2DIcon, AudioMixerGroupIcon, AudioMixerSnapshotIcon, AudioSpatializerMicrosoftIcon,
        AudioChorusFilterIcon, AudioClipIcon, AudioDistortionFilterIcon, AudioEchoFilterIcon,
        AudioHighPassFilterIcon, AudioListenerIcon, AudioLowPassFilterIcon, AudioReverbFilterIcon,
        AudioReverbZoneIcon, AudioSourceIcon, AvatarIcon, AvatarMaskIcon, BillboardAssetIcon,
        BillboardRendererIcon, BoxColliderIcon, BoxCollider2DIcon, BuoyancyEffector2DIcon, CameraIcon,
        CanvasIcon, CanvasGroupIcon, CanvasRendererIcon, CapsuleColliderIcon, CapsuleCollider2DIcon,
        CharacterControllerIcon, CharacterJointIcon, CircleCollider2DIcon, ClothIcon,
        CompositeCollider2DIcon, ComputeShaderIcon, ConfigurableJointIcon, ConstantForceIcon,
        ConstantForce2DIcon, CubemapIcon, dCanvasIcon, dCanvasGroupIcon, dCanvasRendererIcon,
        dGameObjectIcon, dLightProbeProxyVolumeIcon, dParticleSystemIcon, dParticleSystemForceFieldIcon,
        dRectTransformIcon, dStreamingControllerIcon, DistanceJoint2DIcon, EdgeCollider2DIcon,
        dEventSystemIcon, dEventTriggerIcon, dPhysics2DRaycasterIcon, dPhysicsRaycasterIcon,
        dStandaloneInputModuleIcon, dTouchInputModuleIcon, EventSystemIcon, EventTriggerIcon,
        HoloLensInputModuleIcon, Physics2DRaycasterIcon, PhysicsRaycasterIcon, StandaloneInputModuleIcon,
        TouchInputModuleIcon, SpriteShapeRendererIcon, VisualTreeAssetIcon, dVisualEffectIcon,
        dVisualEffectAssetIcon, VisualEffectIcon, VisualEffectAssetIcon, FixedJointIcon,
        FixedJoint2DIcon, FlareIcon, FlareLayerIcon, FontIcon, FrictionJoint2DIcon,
        GameObjectIcon, GridIcon, GUILayerIcon, GUISkinIcon, GUITextIcon, GUITextureIcon,
        HaloIcon, HingeJointIcon, HingeJoint2DIcon, LensFlareIcon, LightIcon, LightProbeGroupIcon,
        LightProbeProxyVolumeIcon, LightProbesIcon, LineRendererIcon, LODGroupIcon, MaterialIcon,
        MeshIcon, MeshColliderIcon, MeshFilterIcon, MeshRendererIcon, MotionIcon, MovieTextureIcon,
        NetworkAnimatorIcon, NetworkDiscoveryIcon, NetworkIdentityIcon, NetworkLobbyManagerIcon,
        NetworkLobbyPlayerIcon, NetworkManagerIcon, NetworkManagerHUDIcon, NetworkMigrationManagerIcon,
        NetworkProximityCheckerIcon, NetworkStartPositionIcon, NetworkTransformIcon,
        NetworkTransformChildIcon, NetworkTransformVisualizerIcon, NetworkViewIcon, OcclusionAreaIcon,
        OcclusionPortalIcon, ParticleSystemIcon, ParticleSystemForceFieldIcon, PhysicMaterialIcon,
        PhysicsMaterial2DIcon, PlatformEffector2DIcon, dPlayableDirectorIcon, PlayableDirectorIcon,
        PointEffector2DIcon, PolygonCollider2DIcon, ProceduralMaterialIcon, ProjectorIcon,
        RectTransformIcon, ReflectionProbeIcon, RelativeJoint2DIcon, dSortingGroupIcon,
        SortingGroupIcon, RenderTextureIcon, RigidbodyIcon, Rigidbody2DIcon, ScriptableObjectIcon,
        ShaderIcon, ShaderVariantCollectionIcon, SkinnedMeshRendererIcon, SkyboxIcon, SliderJoint2DIcon,
        TrackedPoseDriverIcon, SphereColliderIcon, SpringJointIcon, SpringJoint2DIcon, SpriteIcon,
        SpriteMaskIcon, SpriteRendererIcon, StreamingControllerIcon, StyleSheetIcon, SurfaceEffector2DIcon,
        TargetJoint2DIcon, TerrainIcon, TerrainColliderIcon, TerrainDataIcon, TextAssetIcon,
        TextMeshIcon, TextureIcon, Texture2DIcon, TileIcon, TilemapIcon, TilemapCollider2DIcon,
        TilemapRendererIcon, dTimelineAssetIcon, TimelineAssetIcon, TrailRendererIcon, TransformIcon,
        SpriteAtlasIcon, AspectRatioFitterIcon, ButtonIcon, CanvasScalerIcon, ContentSizeFitterIcon,
        dAspectRatioFitterIcon, dCanvasScalerIcon, dContentSizeFitterIcon, dFreeformLayoutGroupIcon,
        dGraphicRaycasterIcon, dGridLayoutGroupIcon2, dHorizontalLayoutGroupIcon2, dLayoutElementIcon,
        dPhysicalResolutionIcon, dScrollViewAreaIcon, dSelectionListIcon, dSelectionListItemIcon,
        dSelectionListTemplateIcon, dVerticalLayoutGroupIcon2, DropdownIcon, FreeformLayoutGroupIcon,
        GraphicRaycasterIcon, GridLayoutGroupIcon, HorizontalLayoutGroupIcon2, ImageIcon, InputFieldIcon,
        LayoutElementIcon, MaskIcon, OutlineIcon, PositionAsUV1Icon, RawImageIcon, RectMask2DIcon,
        ScrollbarIcon, ScrollRectIcon, SelectableIcon, ShadowIcon, SliderIcon, TextIcon, ToggleIcon,
        ToggleGroupIcon, VerticalLayoutGroupIcon, VideoClipIcon, VideoPlayerIcon, VisualEffectIcon2,
        VisualEffectAssetIcon2, WheelColliderIcon, WheelJoint2DIcon, WindZoneIcon,
        SpatialMappingColliderIcon, SpatialMappingRendererIcon, WorldAnchorIcon, UssScriptIcon,
        UxmlScriptIcon, VerticalLayoutGroupIcon2, VideoEffectIcon, VisualEffectGizmo,
        VisualEffectAssetIcon3, AnchorBehaviourIcon, AnchorInputListenerBehaviourIcon,
        AnchorStageBehaviourIcon, CloudRecoBehaviourIcon, ContentPlacementBehaviourIcon,
        ContentPositioningBehaviourIcon, CylinderTargetBehaviourIcon, dAnchorBehaviourIcon,
        dAnchorInputListenerBehaviourIcon, dAnchorStageBehaviourIcon, dCloudRecoBehaviourIcon,
        dContentPlacementBehaviourIcon, dContentPositioningBehaviourIcon, dCylinderTargetBehaviourIcon,
        dImageTargetBehaviourIcon, dMidAirPositionerBehaviourIcon, dModelTargetBehaviourIcon,
        dMultiTargetBehaviourIcon, dObjectTargetBehaviourIcon, dPlaneFinderBehaviourIcon,
        dUserDefinedTargetBuildingBehaviourIcon, dVirtualButtonBehaviourIcon, dVuforiaBehaviourIcon,
        dVuMarkBehaviourIcon, dWireframeBehaviourIcon, ImageTargetBehaviourIcon,
        MidAirPositionerBehaviourIcon, ModelTargetBehaviourIcon, MultiTargetBehaviourIcon,
        ObjectTargetBehaviourIcon, PlaneFinderBehaviourIcon, UserDefinedTargetBuildingBehaviourIcon,
        VirtualButtonBehaviourIcon, VuforiaBehaviourIcon, VuMarkBehaviourIcon, WireframeBehaviourIcon,
        WindZoneGizmo, ProfilerAudio, ProfilerCPU, ProfilerFirstFrame, ProfilerGlobalIllumination,
        ProfilerGPU, ProfilerInstrumentation, ProfilerLastFrame, ProfilerMemory, ProfilerNetworkMessages,
        ProfilerNetworkOperations, ProfilerNextFrame, ProfilerPhysics, ProfilerPhysics2D,
        ProfilerPrevFrame, ProfilerRecord, ProfilerRendering, ProfilerUI, ProfilerUIDetails,
        ProfilerVideo, ProfilerColumnWarningCount, Project, RectToolOn, RectTool, RectTransformBlueprint,
        RectTransformRaw, redGroove, Refresh, renderdoc, rightBracket, RotateToolOn, RotateTool,
        SaveActive, SaveFromPlay, SavePassive, ScaleToolOn, ScaleTool, SceneLoadIn, SceneLoadOut,
        SceneSave, SceneSaveGrey, SceneViewAlpha, SceneViewAudio, SceneViewFx, SceneViewLighting,
        SceneViewOrtho, SceneViewRGB, ScrollShadow, Settings, SettingsIcon, SocialNetworksFacebookShare,
        SocialNetworksLinkedInShare, SocialNetworksTweet, SocialNetworksUDNLogo, SocialNetworksUDNOpen,
        SoftlockInline, SpeedScale, StateMachineEditorArrowTip, StateMachineEditorArrowTipSelected,
        StateMachineEditorBackground, StateMachineEditorState, StateMachineEditorStateHover,
        StateMachineEditorStateSelected, StateMachineEditorStateSub, StateMachineEditorStateSubHover,
        StateMachineEditorStateSubSelected, StateMachineEditorUpButton, StateMachineEditorUpButtonHover,
        StepButtonOn, StepButton, StepLeftButtonOn, StepLeftButton, stickyarrow, stickyp4, stickyskin,
        svicondot0sml, svicondot10sml, svicondot11sml, svicondot12sml, svicondot13sml,
        svicondot14sml, svicondot15sml, svicondot1sml, svicondot2sml, svicondot3sml,
        svicondot4sml, svicondot5sml, svicondot6sml, svicondot7sml, svicondot8sml,
        svicondot9sml, sviconname0, sviconname1, sviconname2, sviconname3, sviconname4,
        sviconname5, sviconname6, sviconname7, sviconnone, svlabel0, svlabel1, svlabel2,
        svlabel3, svlabel4, svlabel5, svlabel6, svlabel7, SVNAddedLocal, SVNConflicted,
        SVNDeletedLocal, SVNLocal, SVNLockedLocal, SVNOutOfSync, tabnext, tabnext2x, tabprev,
        tabprev2x, TerrainInspectorTerrainToolLowerOn, TerrainInspectorTerrainToolLower,
        TerrainInspectorTerrainToolLowerAlt, TerrainInspectorTerrainToolPlantsOn,
        TerrainInspectorTerrainToolPlants, TerrainInspectorTerrainToolPlantsAltOn,
        TerrainInspectorTerrainToolPlantsAlt, TerrainInspectorTerrainToolRaiseOn,
        TerrainInspectorTerrainToolRaise, TerrainInspectorTerrainToolSculptOn,
        TerrainInspectorTerrainToolSculpt, TerrainInspectorTerrainToolSetheightOn,
        TerrainInspectorTerrainToolSetheight, TerrainInspectorTerrainToolSetheightAltOn,
        TerrainInspectorTerrainToolSetheightAlt, TerrainInspectorTerrainToolSettingsOn,
        TerrainInspectorTerrainToolSettings, TerrainInspectorTerrainToolSmoothHeightOn,
        TerrainInspectorTerrainToolSmoothHeight, TerrainInspectorTerrainToolSplatOn,
        TerrainInspectorTerrainToolSplat, TerrainInspectorTerrainToolSplatAltOn,
        TerrainInspectorTerrainToolSplatAlt, TerrainInspectorTerrainToolTreesOn,
        TerrainInspectorTerrainToolTrees, TerrainInspectorTerrainToolTreesAltOn,
        TerrainInspectorTerrainToolTreesAlt, TestFailed, TestIgnored, TestInconclusive, TestNormal,
        TestPassed, TestStopwatch, TimelineClipBG, TimelineClipFG, TimelineDigIn, TimelineEditModeMixOFF,
        TimelineEditModeMixON, TimelineEditModeReplaceOFF, TimelineEditModeReplaceON, TimelineEditModeRippleOFF,
        TimelineEditModeRippleON, TimelineSelector, ToolbarMinus, ToolbarPlusMore, ToolbarPlus,
        ToolHandleCenter, ToolHandleGlobal, ToolHandleLocal, ToolHandlePivot, tranp, TransformToolOn,
        TransformTool, treeicon, treeiconbranch, treeiconbranchfrond, treeiconfrond, treeiconleaf,
        TreeEditorAddBranches, TreeEditorAddLeaves, TreeEditorBranchOn, TreeEditorBranch,
        TreeEditorBranchFreeHandOn, TreeEditorBranchFreeHand, TreeEditorBranchRotateOn,
        TreeEditorBranchRotate, TreeEditorBranchScaleOn, TreeEditorBranchScale,
        TreeEditorBranchTranslateOn, TreeEditorBranchTranslate, TreeEditorDistributionOn,
        TreeEditorDistribution, TreeEditorDuplicate, TreeEditorGeometryOn, TreeEditorGeometry,
        TreeEditorLeafOn, TreeEditorLeaf, TreeEditorLeafFreeHandOn, TreeEditorLeafFreeHand,
        TreeEditorLeafRotateOn, TreeEditorLeafRotate, TreeEditorLeafScaleOn, TreeEditorLeafScale,
        TreeEditorLeafTranslateOn, TreeEditorLeafTranslate, TreeEditorMaterialOn, TreeEditorMaterial,
        TreeEditorRefresh, TreeEditorTrash, TreeEditorWindOn, TreeEditorWind, UnityEditorAnimationWindow,
        UnityEditorConsoleWindow, UnityEditorDebugInspectorWindow, UnityEditorFindDependencies,
        UnityEditorGameView, UnityEditorGraphsAnimatorControllerTool, UnityEditorHierarchyWindow,
        UnityEditorInspectorWindow, UnityEditorLookDevView, UnityEditorProfilerWindow,
        UnityEditorSceneHierarchyWindow, UnityEditorSceneView, UnityEditorTimelineTimelineWindow,
        UnityEditorVersionControl, UnityLogo, UnityLogoLarge, UpArrow, vcsadd, vcsbranch, vcschange,
        vcscheck, vcsdelete, vcsdocument, vcsedit, vcsincoming, vcsintegrate, vcslocal, vcslock,
        vcsrefresh, vcssync, vcsunresolved, vcsupdate, VerticalSplit, ViewToolMoveOn, ViewToolMove,
        ViewToolOrbitOn, ViewToolOrbit, ViewToolZoomOn, ViewToolZoom, VisibilityOff, VisibilityOn,
        VisualEffectGizmo2, VUMeterTextureHorizontal, VUMeterTextureVertical, WaitSpin00, WaitSpin01,
        WaitSpin02, WaitSpin03, WaitSpin04, WaitSpin05, WaitSpin06, WaitSpin07, WaitSpin08, WaitSpin09,
        WaitSpin10, WaitSpin11, WelcomeScreenAssetStoreLogo, winbtngraph, winbtngraphcloseh,
        winbtngraphmaxh, winbtngraphminh, winbtnmacclose, winbtnmacclosea, winbtnmaccloseh,
        winbtnmacinact, winbtnmacmax, winbtnmacmaxa, winbtnmacmaxh, winbtnmacmin,
        winbtnmacmina, winbtnmacminh, winbtnwinclose, winbtnwinclosea, winbtnwincloseh,
        winbtnwinmax, winbtnwinmaxa, winbtnwinmaxh, winbtnwinmin, winbtnwinmina,
        winbtnwinminh, winbtnwinrest, winbtnwinresta, winbtnwinresth,
        AvatarInspectorRightFingersIk, AvatarInspectorLeftFingersIk, AvatarInspectorRightFeetIk,
        AvatarInspectorLeftFeetIk, AvatarInspectorRightFingers, AvatarInspectorLeftFingers,
        AvatarInspectorRightArm, AvatarInspectorLeftArm, AvatarInspectorRightLeg, AvatarInspectorLeftLeg,
        AvatarInspectorHead, AvatarInspectorTorso, AvatarInspectorMaskEditorRoot,
        AvatarInspectorBodyPartPicker, AvatarInspectorBodySIlhouette, booScriptIcon, jsScriptIcon,
        EyeDropperLarge, AboutWindowMainHeader, AgeiaLogo, MonoLogo, PlayButtonProfileAnim,
        StepButtonAnim, PauseButtonAnim, PlayButtonAnim, MoveToolOn, IconDropdown,
        AvatarInspectorDotSelection, AvatarInspectorDotFrameDotted, AvatarInspectorDotFrame,
        AvatarInspectorDotFill, AvatarInspectorRightHandZoom, AvatarInspectorLeftHandZoom,
        AvatarInspectorHeadZoom, AvatarInspectorRightLeg2, AvatarInspectorLeftLeg2,
        AvatarInspectorRightFingers2, AvatarInspectorRightArm2, AvatarInspectorLeftFingers2,
        AvatarInspectorLeftArm2, AvatarInspectorHead2, AvatarInspectorTorso2,
        AvatarInspectorRightHandZoomSilhouette, AvatarInspectorLeftHandZoomSilhouette,
        AvatarInspectorHeadZoomSilhouette, AvatarInspectorBodySilhouette, lightMeterredLight,
        lightMeterorangeLight, lightMeterlightRim, lightMetergreenLight, SceneviewAudio,
        SceneviewLighting, TerrainInspectorTerrainToolSetHeight, ASBadgeNew, ASBadgeMove,
        ASBadgeDelete, WelcomeScreenUnityAnswersLogo, WelcomeScreenUnityForumLogo,
        WelcomeScreenUnityBasicsLogo, WelcomeScreenVideoTutLogo, WelcomeScreenMainHeader, IconDropdown2,
        PrefabNormalIcon, PrefabNormalIcon2, BuildSettingsBlackBerrySmall, BuildSettingsTizenSmall,
        BuildSettingsXBox360Small, BuildSettingsPS3Small, BuildSettingsSamsungTVSmall,
        BuildSettingsBlackBerry, BuildSettingsTizen, BuildSettingsXBox360, BuildSettingsPS3,
        BuildSettingsSamsungTV
    }
}